name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=swiggy
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t swiggy-clone .

      - name: Push to DockerHub
        run: |
          docker tag swiggy-clone ${{ secrets.Dockerhub_username }}/swiggy-clone:latest
          docker login -u ${{ secrets.Dockerhub_username }} -p ${{ secrets.Dockerhub_token }}
          docker push ${{ secrets.Dockerhub_username }}/swiggy-clone:latest

